version: '3'

services:
    jupytertorch:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 8888:8888
        volumes:
            - ..:/data
    
    tensorboard:
        build:
            context: .
            dockerfile: ./Dockerfile-Tensorboard
        ports:
            - 6006:6006
        volumes:
           - ..:/data
        command: ["--logdir", "pytorch_earthquake_recognition/experiment/vizualize/logs"]
